from typing import Final

DATA: Final = {
  'worldPositionX': 'float',
  'worldPositionY': 'float',
  'worldPositionZ': 'float',
  'worldVelocityX': 'float',
  'worldVelocityY': 'float',
  'worldVelocityZ': 'float',
  'worldForwardDirX': 'int16',
  'worldForwardDirY': 'int16',
  'worldForwardDirZ': 'int16',
  'worldRightDirX': 'int16',
  'worldRightDirY': 'int16',
  'worldRightDirZ': 'int16',
  'gForceLateral': 'float',
  'gForceLongitudinal': 'float',
  'gForceVertical': 'float',
  'yaw': 'float',
  'pitch': 'float',
  'roll': 'float',
}

PACKET: Final = {
  'carMotionData': 22 * [DATA],
  'suspensionPosition': 4 * ['float'],
  'suspensionVelocity': 4 * ['float'],
  'suspensionAcceleration': 4 * ['float'],
  'wheelSpeed': 4 * ['float'],
  'wheelSlip': 4 * ['float'],
  'localVelocityX': 'float',
  'localVelocityY': 'float',
  'localVelocityZ': 'float',
  'angularVelocityX': 'float',
  'angularVelocityY': 'float', 
  'angularVelocityZ': 'float',
  'angularAccelerationX': 'float',
  'angularAccelerationY': 'float',
  'angularAccelerationZ': 'float',
  'frontWheelsAngle': 'float',
}
