from typing import Final

MARSHAL_ZONE: Final = {
  'zoneStart': 'float',
  'zoneFlag': 'int8',
}

WEATHER_FORECAST_SAMPLE: Final = {
  'sessionType': 'uint8',
  'timeOffset': 'uint8',
  'weather': 'uint8',
  'trackTemperature': 'int8',
  'trackTemperatureChange': 'int8',
  'airTemperature': 'int8',
  'airTemperatureChange': 'int8',
  'rainPercentage': 'uint8',
}

PACKET: Final = {
    'weather': 'uint8',
    'trackTemperature': 'int8',
    'airTemperature': 'int8',
    'totalLaps': 'uint8',
    'trackLength': 'uint16',
    'sessionType': 'uint8',
    'trackId': 'int8',
    'formula': 'uint8',
    'sessionTimeLeft': 'uint16',
    'sessionDuration': 'uint16',
    'pitSpeedLimit': 'uint8',
    'gamePaused': 'uint8',
    'isSpectating': 'uint8',
    'spectatorCarIndex': 'uint8',
    'sliProNativeSupport': 'uint8',
    'numMarshalZones': 'uint8',
    'marshalZones': 21 * [MARSHAL_ZONE],
    'safetyCarStatus': 'uint8',
    'networkGame': 'uint8',
    'numWeatherForecastSamples': 'uint8',
    'weatherForecastSamples': 56 * [WEATHER_FORECAST_SAMPLE],
    'forecastAccuracy': 'uint8',
    'aiDifficulty': 'uint8',
    'seasonLinkIdentifier': 'uint32',
    'weekendLinkIdentifier': 'uint32',
    'sessionLinkIdentifier': 'uint32',
    'pitStopWindowIdealLap': 'uint8',
    'pitStopWindowLatestLap': 'uint8',
    'pitStopRejoinPosition': 'uint8',
    'steeringAssist': 'uint8',
    'brakingAssist': 'uint8',
    'gearboxAssist': 'uint8',
    'pitAssist': 'uint8',
    'pitReleaseAssist': 'uint8',
    'ERSAssist': 'uint8',
    'DRSAssist': 'uint8',
    'dynamicRacingLine': 'uint8',
    'dynamicRacingLineType': 'uint8',
    'gameMode': 'uint8',
    'ruleSet': 'uint8',
    'timeOfDay': 'uint32',
    'sessionLength': 'uint8',
}
